name: task_manager_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  retrofit: ^4.9.2
  json_annotation: ^4.9.0
  talker_flutter: ^5.1.10
  talker_dio_logger: ^5.1.10
  get_it: ^9.2.0
  go_router: ^17.0.1
  fpdart: ^1.2.0
  intl: ^0.20.2
  google_fonts: ^7.0.2
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  retrofit_generator: ^10.2.1
  json_serializable: ^6.11.4
  mocktail: ^1.0.4
  freezed: ^3.2.4

flutter:
  uses-material-design: true