name: task_manager_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^7.0.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  retrofit: ^4.9.2
  talker_dio_logger: ^5.1.10
  talker_flutter: ^5.1.10

dev_dependencies:
  build_runner: ^2.10.5

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  mocktail: ^1.0.4
  retrofit_generator: ^10.2.1

flutter:
  uses-material-design: true
